# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: swoman <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/02/12 19:09:58 by swoman            #+#    #+#              #
#    Updated: 2019/02/12 21:04:05 by swoman           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = do-op

FLAGS = -Wall -Wextra -Werror

OUT = do_op.c signs.c ft.c

INCLUDES = includes/

all:
	gcc $(FLAGS) $(OUT) -I$(INCLUDES) -o $(NAME)

clean:
	rm -f *.o

